### ISSUE TITLE
Split repository into two branches to allow plugins

### ISSUE THREAD

**Issue by kitforbes** [kitforbes/kitforbes.github.io#10]
### Desired functionality

As [GitHub Pages does not allow Jekyll plugins](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/) which are not included in the `github-pages` gem, splitting the repository so that the `master` branch contains only the contents of the generated `_site` folder will allow greater customisation. The source for the site should be maintained within a separate branch.

With this approach, it would be best to incorporate a CI tool to ensure the content is generating correctly before being pushed to `master`.
### Tasks required to achieve functionality
- [ ] Add files needed for Travis CI.
- [ ] Create a build/deploy workflow.
- [ ] Create a `develop` branch.
- [ ] Remove everything from the `master` branch that is not in the `_site` folder.

**Comment by kitforbes** [comment]
No longer required.
