### ISSUE TITLE
Extract theme into a Ruby Gem

### ISSUE THREAD

**Issue by kitforbes** [kitforbes/kitforbes.github.io#12]
### Desired functionality

In order to use the theme in sub-projects as well as this project, I want to extract the relevant theme files and package them in a Ruby Gem.

### Tasks required to achieve functionality

- [ ] Create an account on [RubyGems.org](https://rubygems.org/).
- [ ] Name the theme (the hardest part)
- [ ] Create a new repository to hold the theme.
- [ ] Copy the content to the new repository.
- [ ] Build and push the gem.
- [ ] Remove the theme content and replace it with the gem content.

**Comment by kitforbes** [comment]
No longer required.
